export default {
    products: [
      {
        _id: '1',
        name: 'Mens Limeous white shirt slim fit Size 16',
        category: 'Shirts',
        image: '/images/d1.jpg',
        detailImage1: '/images/d11.jpeg',
        detailImage2: '/images/d12.jpeg',
        detailImage3: '/images/d1.jpg',
        price: 7.00,
        brand: ' Nike',
        size: 'L',
        condition: 'Very Good',
        color: 'White',
        location: 'United Kingdom',
        PaymentOptions: 'Credit Card',
        subCategory: 'Tops & Shirts',
        countInStock: 5
      },
      {
        _id: '2',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: '/images/d1.jpg',
        detailImage1: '/images/d1.jpg',
        detailImage2: '/images/d1.jpg',
        detailImage3: '/images/d1.jpg',
        price: 7.00,
        brand: ' Nike',
        size: 'L',
        condition: 'Very Good',
        color: 'White',
        location: 'United Kingdom',
        PaymentOptions: 'Credit Card',
        subCategory: 'Tops & Shirts',
        countInStock: 0
      },
      {
        _id: '3',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: '/images/d1.jpg',
        detailImage1: '/images/d1.jpg',
        detailImage2: '/images/d1.jpg',
        detailImage3: '/images/d1.jpg',
        price: 7.00,
        brand: ' Nike',
        size: 'L',
        condition: 'Very Good',
        color: 'White',
        location: 'United Kingdom',
        PaymentOptions: 'Credit Card',
        subCategory: 'Tops & Shirts',
        countInStock: 6
      },
      {
        _id: '4',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: '/images/d1.jpg',
        detailImage1: '/images/d1.jpg',
        detailImage2: '/images/d1.jpg',
        detailImage3: '/images/d1.jpg',
        price: 7.00,
        brand: ' Nike',
        size: 'L',
        condition: 'Very Good',
        color: 'White',
        location: 'United Kingdom',
        PaymentOptions: 'Credit Card',
        subCategory: 'Tops & Shirts',
        countInStock: 9
      },
      {
        _id: '5',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: '/images/d1.jpg',
        detailImage1: '/images/d1.jpg',
        detailImage2: '/images/d1.jpg',
        detailImage3: '/images/d1.jpg',
        price: 7.00,
        brand: ' Nike',
        size: 'L',
        condition: 'Very Good',
        color: 'White',
        location: 'United Kingdom',
        PaymentOptions: 'Credit Card',
        subCategory: 'Tops & Shirts',
        countInStock: 4
      }
      
    ]
  }